### ISSUE TITLE
smaller as Highlighting 

### ISSUE THREAD

**Issue by janitz** [rcanedu/stVScode#3]
the smaller as operator seems to be an opening bracket

![image](https://user-images.githubusercontent.com/12070509/27727467-dff13ef8-5d7e-11e7-9506-5b40d9c31d44.png)

workaround:

![image](https://user-images.githubusercontent.com/12070509/27727500-04e9ffba-5d7f-11e7-8c2b-5cbf430d9cc5.png)

**Comment by rcanedu** [comment]
@janitz Do you can show more code?
I do not see this in my workspace.
![image](https://user-images.githubusercontent.com/28677014/27729480-b8bfe748-5d8e-11e7-9901-b5c2af48efbb.png)

**Comment by rcanedu** [comment]
@janitz I did find it. Thanks you

**Comment by janitz** [comment]
i have still the same problem.

I found that removing the
`PROGRAM helloWorld`
at the beginning and the 
`END_PROGRAM` 
at the end of my .st-file solves the problem
