### ISSUE TITLE
Please correct your description or I'll report!

### ISSUE THREAD

**Issue by Serhioromano** [rcanedu/stVScode#8]
You confuse people. In the README you have

> - Code Linting
> - Auto indenting
> - Code formatting
> - Intellisense
> - Snippets

- You DO NOT have linting support
- You DO NOT have code formatting
- You DO NOT have auto indent (only on brackets and that does not counts as it is basic VS code function)
- You DO NOT have any snippets
- You DO NOT have intellicense support on any level even most basic.

So your description is deceiving on all 5 points. Totally unacceptable.

**Comment by auchenberg** [comment]
Hi @rcanedu

It's Kenneth from the VS Code team. It would be helpful if you could update the readme of your extension to accurately reflect what the extension currently provides.

Thanks.

/k
